### PR TITLE
Add license

### PR DESCRIPTION
**Pull request by campagnola**
BSD 3-clause? 
If you click on Insights -> Community, you can browse through other license options.

### CODE REVIEW

**Review by pbmanis — COMMENTED** [review]
This would work (seems similar to the "MIT" license on acq4), but shouldn't your name be on it also? 

There are several places (but not too many) in the code where a license is specified (MIT), so these will need to be corrected, or better, removed (util/Params, util/pyqtgraphPlotHelpers)- except in the doc/numpydoc stuff.

**Comment by campagnola** [comment]
Do you have a preference? I just picked at random. MIT would be fine as well.

**Comment by campagnola** [comment]
Ready!

**Review by pbmanis — APPROVED** [review]
Looks good, merging

**Pull request merged**
